[build]
  command = "npm run build"
  publish = "docs"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[context.production.environment]
  ELEVENTY_PRODUCTION = "true"  # Â¡Ahora entre comillas!